'''
Created on Jul 30, 2019

@author: Tavis
'''

def get_velocity_vortex_details():
    return ["red_auto_beacons",
            "red_auto_cap",
            "red_auto_part_cen",
            "red_auto_part_cor",
            "red_auto_robot_1",
            "red_auto_robot_2",
            "red_tele_beacons",
            "red_tele_part_cen",
            "red_tele_part_cor",
            "red_tele_cap",
            "blue_auto_beacons",
            "blue_auto_cap",
            "blue_auto_part_cen",
            "blue_auto_part_cor",
            "blue_auto_robot_1",
            "blue_auto_robot_2",
            "blue_tele_beacons",
            "blue_tele_part_cen",
            "blue_tele_part_cor",
            "blue_tele_cap"]
def get_relic_recovery_details():
    return ["red_auto_jewels",
            "red_auto_glyphs",
            "red_auto_keys",
            "red_auto_parks",
            "red_tele_glyphs",
            "red_tele_rows",
            "red_tele_cols",
            "red_tele_cyphers",
            "red_end_relic_1",
            "red_end_relic_2",
            "red_end_relic_3",
            "red_end_relic_standing",
            "red_end_robot_balances",
            "blue_auto_jewels",
            "blue_auto_glyphs",
            "blue_auto_keys",
            "blue_auto_parks",
            "blue_tele_glyphs",
            "blue_tele_rows",
            "blue_tele_cols",
            "blue_tele_cyphers",
            "blue_end_relic_1",
            "blue_end_relic_2",
            "blue_end_relic_3",
            "blue_end_relic_standing",
            "blue_end_robot_balances"]
def get_rover_ruckus_details():
    return ["red_auto_land",
            "red_auto_samp",
            "red_auto_claim",
            "red_auto_park",
            "red_tele_gold",
            "red_tele_silver",
            "red_tele_depot",
            "red_end_latch",
            "red_end_in",
            "red_end_comp",
            "blue_auto_land",
            "blue_auto_samp",
            "blue_auto_claim",
            "blue_auto_park",
            "blue_tele_gold",
            "blue_tele_silver",
            "blue_tele_depot",
            "blue_end_latch",
            "blue_end_in",
            "blue_end_comp"]
        